synthetic-package: false
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: chat_bot_localizations.dart
nullable-getter: false
output-dir: lib/localization
prefer-match-language-code: true
required-resource-attributes: false  # Disable required metadata for ARB keys 