name: chat_bot_sdk
description: A Flutter SDK for integrating with Dify.ai Chat API, supporting streaming responses
version: 0.0.1
homepage: https://github.com/yourusername/chat_bot_sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.8.0
  flutter_riverpod: ^2.4.9
  flutter_markdown: ^0.6.18
  uuid: ^4.2.2
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/ 